version: '3.9'
services:
  mysql-gallary:
    container_name: mysql-gallary
    image: mysql
    ports:
      - 13306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ele_art-gallary_17
      - MYSQL_PASSWORD=ele_art-gallary_17
      - MYSQL_USER=ela-art
      - MYSQL_DATABASE=gallary
    volumes:
      - ./mysqlDB:/var/lib/meinsql/data
  phpmyadmin-gallary:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-gallary
    depends_on:
        - mysql-gallary
    environment:
        PMA_HOST: mysql-gallary
    restart: always
    ports:
        - 19090:80